

import { ResourceCategory } from '../types';

export const examCategories = [
  {
    name: "Genel Deneme Sınavları",
    topics: ["TYT", "AYT"],
  },
  {
    name: "Matematik",
    topics: [
      "Temel Kavramlar",
      "Sayı Basamakları",
      "Bölme ve Bölünebilme",
      "OBEB-OKEK",
      "Rasyonel Sayılar",
      "Basit Eşitsizlikler",
      "Mutlak Değer",
      "Üslü Sayılar",
      "Köklü Sayılar",
      "Çarpanlara Ayırma",
      "Oran-Orantı",
      "Problemler",
      "Mantık",
      "Kümeler",
      "Fonksiyonlar",
      "Polinomlar",
      "İkinci Dereceden Denklemler",
      "Permütasyon-Kombinasyon",
      "Olasılık",
      "İstatistik",
      "Trigonometri",
      "Logaritma",
      "Diziler",
      "Limit ve Süreklilik",
      "Türev",
      "İntegral",
    ],
  },
  {
    name: "Geometri",
    topics: [
        "Temel Kavramlar",
        "Üçgende Açılar",
        "Özel Üçgenler",
        "Üçgende Alan",
        "Açıortay-Kenarortay",
        "Çokgenler",
        "Dörtgenler",
        "Çember ve Daire",
        "Analitik Geometri",
        "Katı Cisimler",
    ]
  },
  {
    name: "Fizik",
    topics: [
      "Fizik Bilimine Giriş",
      "Madde ve Özellikleri",
      "Sıvıların Kaldırma Kuvveti",
      "Basınç",
      "Isı, Sıcaklık ve Genleşme",
      "Hareket ve Kuvvet",
      "Dinamik",
      "İş, Güç ve Enerji",
      "Elektrik",
      "Manyetizma",
      "Optik",
      "Dalgalar",
      "Modern Fizik",
    ],
  },
  {
    name: "Kimya",
    topics: [
      "Kimya Bilimi",
      "Atom ve Periyodik Sistem",
      "Kimyasal Türler Arası Etkileşimler",
      "Maddenin Halleri",
      "Mol Kavramı",
      "Kimyasal Tepkimeler ve Hesaplamalar",
      "Asitler, Bazlar ve Tuzlar",
      "Karışımlar",
      "Kimya Her Yerde",
      "Organik Kimya",
      "Kimyasal Denge",
      "Çözünürlük Dengesi",
      "Elektrokimya",
    ],
  },
  {
    name: "Biyoloji",
    topics: [
      "Canlıların Ortak Özellikleri",
      "Canlıların Temel Bileşenleri",
      "Hücre ve Organelleri",
      "Hücre Bölünmeleri",
      "Kalıtım",
      "Ekosistem Ekolojisi",
      "Sinir Sistemi",
      "Endokrin Sistem",
      "Dolaşım Sistemi",
      "Solunum Sistemi",
      "Boşaltım Sistemi",
      "Bitki Biyolojisi",
      "Genden Proteine",
    ],
  },
  {
    name: "Türkçe",
    topics: [
      "Sözcükte Anlam",
      "Cümlede Anlam",
      "Paragraf",
      "Ses Bilgisi",
      "Yazım Kuralları",
      "Noktalama İşaretleri",
      "Sözcük Yapısı",
      "Fiiller",
      "Zamirler",
      "Sıfatlar",
      "Zarflar",
      "Cümlenin Öğeleri",
      "Anlatım Bozuklukları",
    ],
  },
  {
    name: "Edebiyat",
    topics: [
        "Güzel Sanatlar ve Edebiyat",
        "Şiir Bilgisi",
        "İslamiyet Öncesi Türk Edebiyatı",
        "Divan Edebiyatı",
        "Halk Edebiyatı",
        "Tanzimat Edebiyatı",
        "Servet-i Fünun Edebiyatı",
        "Milli Edebiyat",
        "Cumhuriyet Dönemi Edebiyatı",
    ]
  },
  {
    name: "Tarih",
    topics: [
      "Tarih ve Zaman",
      "İlk Çağ Uygarlıkları",
      "İslam Tarihi ve Uygarlığı",
      "Türk-İslam Devletleri",
      "Osmanlı Devleti Kuruluş ve Yükselme",
      "Osmanlı Devleti Duraklama ve Gerileme",
      "19. Yüzyılda Osmanlı",
      "Kurtuluş Savaşı",
      "Atatürk İlke ve İnkılapları",
      "Çağdaş Türk ve Dünya Tarihi",
    ],
  },
  {
    name: "Coğrafya",
    topics: [
      "Doğa ve İnsan",
      "Harita Bilgisi",
      "Dünya'nın Şekli ve Hareketleri",
      "İklim Bilgisi",
      "Türkiye'nin İklimi",
      "İç ve Dış Kuvvetler",
      "Nüfus ve Yerleşme",
      "Ulaşım Yolları",
      "Bölgeler ve Ülkeler",
      "Çevre ve Toplum",
    ],
  },
  {
    name: "Felsefe",
    topics: [
        "Felsefeye Giriş",
        "Bilgi Felsefesi",
        "Varlık Felsefesi",
        "Ahlak Felsefesi",
        "Siyaset Felsefesi",
        "Din Felsefesi",
        "Sanat Felsefesi",
    ]
  }
];

export const ResourceCategoryLabels: Record<ResourceCategory, string> = {
    [ResourceCategory.Matematik]: 'Matematik',
    [ResourceCategory.Fizik]: 'Fizik',
    [ResourceCategory.Kimya]: 'Kimya',
    [ResourceCategory.Biyoloji]: 'Biyoloji',
    [ResourceCategory.Turkce]: 'Türkçe',
    [ResourceCategory.Tarih]: 'Tarih',
    [ResourceCategory.Cografya]: 'Coğrafya',
    [ResourceCategory.Felsefe]: 'Felsefe',
    [ResourceCategory.Ingilizce]: 'İngilizce',
    [ResourceCategory.Genel]: 'Genel Kaynaklar',
};