import { UserRole, AssignmentStatus, BadgeID, AcademicTrack, ResourceCategory } from '../types';

export const seedData = {
  assignments: [
    // --- LEYLA'NIN ÖDEVLERİ ---
    {
      title: "Matematik: Türev Alma Kuralları Testi",
      description: "Türev alma kurallarını içeren 20 soruluk testi çözün ve sonuçlarınızı yükleyin. Özellikle çarpım ve bölüm türevine odaklanın.",
      dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      status: AssignmentStatus.Pending,
      studentId: "STUDENT_1_ID",
      coachId: "COACH_ID",
      submissionType: 'file',
      checklist: [ { text: "Konu tekrarı yapıldı." }, { text: "20 soru çözüldü." }, { text: "Yanlışlar kontrol edildi." } ],
      grade: null, feedback: '', fileUrl: null, submittedAt: null,
    },
    {
      title: "Türkçe: Paragraf Soru Çözümü",
      description: "Verilen kaynaktan 50 paragraf sorusu çözülecek.",
      dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      status: AssignmentStatus.Graded,
      studentId: "STUDENT_1_ID",
      coachId: "COACH_ID",
      submissionType: 'completed',
      grade: 95, feedback: 'Harika bir iş çıkardın Leyla! Paragraf anlama hızın ve doğruluğun gözle görülür şekilde artmış. Bu tempoyu koru!', fileUrl: null, submittedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
     {
      title: "Biyoloji: Hücre Bölünmeleri Karşılaştırma",
      description: "Mitoz ve Mayoz bölünmenin evrelerini Venn şeması kullanarak karşılaştırın. Farklılıkları ve ortak yönleri belirtin.",
      dueDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
      status: AssignmentStatus.Pending,
      studentId: "STUDENT_1_ID",
      coachId: "COACH_ID",
      submissionType: 'file',
      grade: null, feedback: '', fileUrl: null, submittedAt: null,
    },
    // --- MEHMET'İN ÖDEVLERİ ---
    {
      title: "Fizik: Vektörler Konu Özeti",
      description: "Fizik dersi vektörler konusunun özetini çıkarıp metin olarak gönderin. Bileşke vektör bulma yöntemlerine özellikle değinin.",
      dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
      status: AssignmentStatus.Pending,
      studentId: "STUDENT_2_ID",
      coachId: "COACH_ID",
      submissionType: 'text',
      grade: null, feedback: '', fileUrl: null, submittedAt: null,
    },
    {
      title: "Kimya: Mol Kavramı Soru Bankası",
      description: "Soru bankasındaki mol kavramı ile ilgili ilk 3 testi bitir.",
      dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      status: AssignmentStatus.Submitted,
      studentId: "STUDENT_2_ID",
      coachId: "COACH_ID",
      submissionType: 'completed',
      grade: null, feedback: '', fileUrl: null, submittedAt: new Date().toISOString(),
    },
    {
      title: "Tarih: Kurtuluş Savaşı Cepheler Sunumu",
      description: "Kurtuluş Savaşı cephelerini özetleyen kısa bir sunum hazırla. Her cephe için önemli bir olayı vurgula.",
      dueDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      status: AssignmentStatus.Graded,
      studentId: "STUDENT_2_ID",
      coachId: "COACH_ID",
      submissionType: 'file',
      grade: 88, feedback: 'Mehmet, sunumun içeriği gayet iyiydi. Görsel kullanımı ve sadelik konuyu daha anlaşılır kılmış. Zaman yönetimi konusunda biraz daha pratik yapabilirsin. Eline sağlık.', fileUrl: null, submittedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    },
    // --- ALİ'NİN ÖDEVLERİ ---
     {
      title: "Geometri: Üçgenlerde Alan Formülleri",
      description: "Tüm üçgenlerde alan formüllerini bir kağıda yaz ve örnek birer soru çözümü ekle.",
      dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
      status: AssignmentStatus.Pending,
      studentId: "STUDENT_3_ID",
      coachId: "COACH_ID",
      submissionType: 'file',
      grade: null, feedback: '', fileUrl: null, submittedAt: null,
    },
     {
      title: "Edebiyat: Divan Edebiyatı Sanatçıları",
      description: "17. Yüzyıl Divan Edebiyatı'nın 3 önemli şairini ve eserlerini araştırarak kısa bir metin hazırla.",
      dueDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      status: AssignmentStatus.Graded,
      studentId: "STUDENT_3_ID",
      coachId: "COACH_ID",
      submissionType: 'text',
      grade: 92, feedback: "Ali, araştrman çok detaylı ve bilgilendirici olmuş. Özellikle Nabi'nin üslubunu iyi yakalamışsın. Böyle devam et!", fileUrl: null, submittedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    // --- ELİF'İN ÖDEVLERİ ---
    {
      title: "Coğrafya: Türkiye'nin Gölleri",
      description: "Türkiye'nin tektonik, karstik ve volkanik göllerine 3'er örnek vererek harita üzerinde göster.",
      dueDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
      status: AssignmentStatus.Pending,
      studentId: "STUDENT_4_ID",
      coachId: "COACH_2_ID",
      submissionType: 'file',
      grade: null, feedback: '', fileUrl: null, submittedAt: null,
    },
    {
      title: "İngilizce: Kelime Çalışması",
      description: "Verilen 20 kelimeyi ezberle ve her biriyle birer cümle kur.",
      dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      status: AssignmentStatus.Submitted,
      studentId: "STUDENT_4_ID",
      coachId: "COACH_2_ID",
      submissionType: 'text',
      grade: null, feedback: '', fileUrl: null, submittedAt: new Date(Date.now() - 1 * 12 * 60 * 60 * 1000).toISOString(),
    },
  ],
  conversations: [
    { id: "conv-1", participantIds: ["COACH_ID", "STUDENT_1_ID"], isGroup: false },
    { id: "conv-2", participantIds: ["COACH_ID", "STUDENT_2_ID"], isGroup: false },
    { id: "conv-3", participantIds: ["COACH_ID", "STUDENT_3_ID"], isGroup: false },
    { id: "conv-4", participantIds: ["COACH_2_ID", "STUDENT_4_ID"], isGroup: false },
    {
      id: 'conv-announcements',
      participantIds: ["COACH_ID", "STUDENT_1_ID", "STUDENT_2_ID", "STUDENT_3_ID"],
      isGroup: true,
      groupName: "📢 Ahmet Hoca Duyurular",
      adminId: "COACH_ID",
    },
    {
      id: 'conv-group-1',
      participantIds: ["COACH_ID", "STUDENT_1_ID", "STUDENT_3_ID"],
      isGroup: true,
      groupName: "Sayısal Çalışma Grubu",
      adminId: "COACH_ID",
    }
  ],
  messages: [
    {
      senderId: "COACH_ID",
      conversationId: "conv-1",
      text: "Merhaba Leyla, haftalık programını gözden geçirdim. Matematik netlerin yükselişte, tebrikler!",
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      type: 'text', readBy: [],
    },
    {
      senderId: "STUDENT_1_ID",
      conversationId: "conv-1",
      text: "Teşekkür ederim öğretmenim! Türev testinde biraz zorlandım ama halledeceğim.",
      timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
      type: 'text', readBy: [],
    },
    {
      senderId: "COACH_ID",
      conversationId: "conv-announcements",
      text: "Arkadaşlar, yarınki deneme sınavı için son tekrar yapmayı unutmayın! Başarılar dilerim.",
      timestamp: new Date().toISOString(),
      type: 'announcement', readBy: [],
    },
     {
      senderId: "COACH_2_ID",
      conversationId: "conv-4",
      text: "Elif merhaba, platforma hoş geldin! İlk ödevlerini atadım, takıldığın bir yer olursa çekinme sorabilirsin.",
      timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
      type: 'text', readBy: [],
    },
     {
      senderId: "STUDENT_4_ID",
      conversationId: "conv-4",
      text: "Hoş buldum hocam, teşekkür ederim. Kelime ödevini teslim ettim.",
      timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
      type: 'text', readBy: [],
    },
    {
      senderId: "COACH_ID",
      conversationId: "conv-group-1",
      text: "Bu hafta sonu hangi konudan ortak bir soru çözüm saati yapalım?",
      timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      type: 'poll',
      poll: {
        question: "Hafta sonu soru çözüm konusu:",
        options: [ { text: "Limit ve Süreklilik", votes: ["STUDENT_1_ID"] }, { text: "Organik Kimya", votes: [] }, { text: "Modern Fizik", votes: ["STUDENT_3_ID"] } ]
      },
      readBy: [],
    }
  ],
  goals: [
    { studentId: "STUDENT_1_ID", text: "Haftada 200 matematik sorusu çözmek.", isCompleted: true },
    { studentId: "STUDENT_1_ID", text: "Türkçe deneme netini 35'in üzerine çıkarmak.", isCompleted: false },
    { studentId: "STUDENT_1_ID", text: "Biyoloji kalıtım konusunu bitirmek.", isCompleted: false },
    { studentId: "STUDENT_2_ID", text: "Fizik Vektörler konusunu tamamen bitirmek.", isCompleted: false },
    { studentId: "STUDENT_2_ID", text: "Her gün 20 paragraf sorusu çözmek.", isCompleted: true },
    { studentId: "STUDENT_3_ID", text: "Geometri katı cisimler konusuna başlamak.", isCompleted: false },
    { studentId: "STUDENT_4_ID", text: "Günde 10 yeni İngilizce kelime öğrenmek.", isCompleted: false },
  ],
  resources: [
    { name: "Türev Konu Anlatımı PDF", type: 'pdf', url: "#", isPublic: true, uploaderId: "COACH_ID", category: ResourceCategory.Matematik },
    { name: "Paragraf Çözme Taktikleri Videosu", type: 'video', url: "#", isPublic: true, uploaderId: "COACH_ID", category: ResourceCategory.Turkce },
    { name: "Limit ve Süreklilik Ders Notları", type: 'document', url: "#", isPublic: true, uploaderId: "COACH_ID", category: ResourceCategory.Matematik },
    { name: "Organik Kimya Özel Notları", type: 'document', url: "#", isPublic: false, uploaderId: "COACH_ID", assignedTo: ["STUDENT_2_ID", "STUDENT_3_ID"], category: ResourceCategory.Kimya },
    { name: "AYT Fizik Denemeleri", type: 'pdf', url: "#", isPublic: false, uploaderId: "COACH_2_ID", assignedTo: ["STUDENT_4_ID"], category: ResourceCategory.Fizik },
    { name: "Coğrafya Harita Çalışması", type: 'image', url: "#", isPublic: true, uploaderId: "COACH_2_ID", category: ResourceCategory.Cografya },
  ],
  templates: [
    { title: "Matematik: Haftalık Tekrar Testi", description: "Bu haftanın konularını içeren tekrar testini çöz.", checklist: [{ text: "Konu tekrarı yapıldı." }, { text: "20 soru çözüldü." }, { text: "Yanlışlar kontrol edildi." }] },
    { title: "Matematik: Logaritma Fonksiyonu", description: "Logaritma fonksiyonunun tanımını, özelliklerini ve kullanım alanlarını öğren. Bol bol soru çözerek konuyu pekiştir.", checklist: [{ text: "Logaritma ve üstel fonksiyon arasındaki ilişkiyi tekrar et." }, { text: "Logaritma özelliklerini (toplama, çıkarma, taban değiştirme) not al." }, { text: "En az 50 logaritma sorusu çöz." }, { text: "Logaritmik denklemler ve eşitsizlikler konusunu çalış." }] },
    { title: "Matematik: Trigonometri Temel Kavramlar", description: "Birim çember, trigonometrik fonksiyonlar (sin, cos, tan, cot), temel özdeşlikler ve trigonometrik denklemler konularını kapsayan bir çalışma yap.", checklist: [{ text: "Birim çember üzerindeki açıların trigonometrik değerlerini ezberle." }, { text: "Toplam-fark ve yarım açı formüllerini kullanarak 20 soru çöz." }, { text: "Trigonometrik denklemlerin çözüm kümelerini bulma alıştırması yap." }] },
    { title: "Geometri: Katı Cisimler", description: "Katı cisimlerin (Prizma, Piramit, Silindir, Koni, Küre) alan ve hacim formüllerini öğren ve bu formülleri kullanarak çeşitli problemleri çöz.", checklist: [{ text: "Her bir katı cismin formülünü bir formül kağıdına çıkar." }, { text: "Her cisimle ilgili en az 10'ar tane alan ve hacim sorusu çöz." }, { text: "Cisimlerin birleşiminden oluşan sorulara odaklan." }, { text: "Çıkmış soruları analiz et." }] },
    { title: "Türkçe: Kitap Özeti", description: "Belirtilen kitabı oku ve bir sayfalık özetini çıkar.", checklist: [{ text: "Kitap okundu." }, { text: "Ana fikir belirlendi." }, { text: "Özet yazıldı." }] },
    { title: "Türkçe: Yazım Kuralları ve Noktalama", description: "TDK'nin güncel yazım kılavuzuna göre yazım kurallarını ve noktalama işaretlerinin kullanımını tekrar et. Bu kurallarla ilgili en az 100 soru çözerek pratik yap.", checklist: [{ text: "Büyük harflerin kullanımı tekrar edildi." }, { text: "Sayıların, kısaltmaların ve 'ki', 'de', 'mi' eklerinin yazımı çalışıldı." }, { text: "Nokta, virgül, noktalı virgül ve diğer işaretlerin kullanım alanları incelendi." }, { text: "En az 100 soru çözüldü ve yanlışlar analiz edildi." }] },
    { title: "Edebiyat: Şiir Tahlili", description: "Belirtilen şiiri; ölçü, uyak, redif, tema, dil ve üslup gibi açılardan inceleyerek bir tahlil metni oluştur.", checklist: [{ text: "Şiirin ölçüsü ve uyak şeması çıkarıldı." }, { text: "Şiirdeki söz sanatları (edebi sanatlar) bulundu." }, { text: "Şiirin teması ve ana duygusu belirlendi." }, { text: "Şairin üslubu ve şiirin ait olduğu dönem hakkında kısa bir yorum yapıldı." }] },
    { title: "Fizik: Optik Konu Tekrarı", description: "Optik ünitesindeki (Gölge, Aydınlanma, Düzlem Ayna, Küresel Aynalar) konularını tekrar et ve ilgili konulardan en az 40 soru çöz.", checklist: [{ text: "Konu anlatım videosu izlendi veya notlar tekrar edildi." }, { text: "En az 40 adet karışık optik sorusu çözüldü." }, { text: "Yapılamayan soruların çözümleri öğrenildi." }, { text: "Önemli formüller ve kurallar not defterine yazıldı." }] },
    { title: "Fizik: Elektrik ve Manyetizma", description: "Elektrik akımı, potansiyel fark, direnç ve Ohm Yasası konularını tekrar et. Manyetik alan ve manyetik kuvvet konularına giriş yap.", checklist: [{ text: "Ohm Yasası ile ilgili 10 adet problem çöz." }, { text: "Seri ve paralel bağlı devrelerde eşdeğer direnci hesapla." }, { text: "Sağ el kuralını ve kullanım alanlarını öğren." }, { text: "Manyetik alan kaynaklarını (düz tel, halka, bobin) çalış." }] },
    { title: "Fizik: Dinamik (Newton'un Hareket Yasaları)", description: "Newton'un üç hareket yasasını anla ve sürtünmeli/sürtünmesiz yüzeyler, eğik düzlem gibi farklı senaryolarda problem çözme pratiği yap.", checklist: [{ text: "Newton'un 3 yasasını kendi cümlelerinle açıkla." }, { text: "Serbest cisim diyagramı çizmeyi öğren." }, { text: "En az 30 adet dinamik problemi çöz." }, { text: "Eylemsizlik ve etki-tepki prensipleri arasındaki farkı anla." }] },
    { title: "Kimya: Organik Kimyaya Giriş", description: "Organik Kimya ünitesinin başlangıç konularını (Basit formül, molekül formülü, hibritleşme, molekül geometrisi) çalış ve temel alıştırmaları yap.", checklist: [{ text: "Konu anlatımı tamamlandı." }, { text: "Hibritleşme (sp, sp2, sp3) türleri tekrar edildi." }, { text: "VSEPR gösterimleri ve molekül geometrileri ezberlendi." }, { text: "En az 20 alıştırma sorusu çözüldü." }] },
    { title: "Kimya: Asitler, Bazlar ve Tuzlar", description: "Asit ve bazların genel özelliklerini, pH kavramını, nötralleşme tepkimelerini ve tuzların özelliklerini öğren.", checklist: [{ text: "Arrhenius, Brønsted-Lowry asit-baz tanımlarını tekrar et." }, { text: "pH ve pOH kavramları ile ilgili hesaplamalar yap." }, { text: "Bir titrasyon deneyinin adımlarını incele." }, { text: "En az 40 soru çözerek konuyu pekiştir." }] },
    { title: "Biyoloji: Hücre Bölünmeleri", description: "Mitoz ve Mayoz bölünmenin evrelerini karşılaştırmalı olarak çalış. Farklılıkları ve ortak yönleri belirten bir tablo hazırla.", checklist: [{ text: "Mitoz bölünme evreleri ve özellikleri çalışıldı." }, { text: "Mayoz bölünme evreleri ve özellikleri çalışıldı." }, { text: "Karşılaştırma tablosu oluşturuldu." }, { text: "İki bölünme türüyle ilgili 20 soru çözüldü." }] },
    { title: "Biyoloji: Kalıtımın Genel İlkeleri", description: "Mendel'in yasalarını, monohibrit, dihibrit çaprazlamaları ve soyağacı analizlerini çalış.", checklist: [{ text: "Mendel'in ilkelerini (benzerlik, ayrılma, bağımsız dağılım) tekrar et." }, { text: "Çaprazlama ile ilgili 20 problem çöz." }, { text: "Kan grupları kalıtımı konusunu çalış." }, { text: "5 farklı soyağacı problemini analiz et." }] },
    { title: "Tarih: Kurtuluş Savaşı Cepheler", description: "Kurtuluş Savaşı'ndaki Doğu, Güney ve Batı cephelerini, önemli komutanları, yapılan savaşları ve sonuçlarını detaylı bir şekilde çalış.", checklist: [{ text: "Doğu ve Güney cepheleri çalışıldı." }, { text: "Batı cephesi savaşları (I. İnönü, II. İnönü, vb.) sırasıyla öğrenildi." }, { text: "Savaşların sonuçları ve imzalanan antlaşmalar not alındı." }, { text: "Konuyla ilgili zaman çizelgesi oluşturuldu." }] },
    { title: "Tarih: Osmanlı Yükselme Dönemi", description: "Fatih Sultan Mehmet'ten Sokullu Mehmet Paşa'nın ölümüne kadar olan dönemin siyasi olaylarını, önemli padişahlarını ve yapılan ıslahatları çalış.", checklist: [{ text: "Dönemin padişahlarını ve önemli olaylarını kronolojik olarak listele." }, { text: "İstanbul'un Fethi'nin neden ve sonuçlarını analiz et." }, { text: "Kanuni Sultan Süleyman dönemindeki seferleri ve antlaşmaları harita üzerinden incele." }, { text: "Coğrafi Keşiflerin Osmanlı'ya etkilerini araştır." }] },
    { title: "Coğrafya: Türkiye'nin İklimi", description: "Türkiye'de görülen iklim tiplerini, etkileyen faktörleri ve bu iklimlerin bitki örtüsü üzerindeki etkilerini harita üzerinden inceleyerek çalış.", checklist: [{ text: "Türkiye'nin iklimini etkileyen faktörler tekrar edildi." }, { text: "İklim tipleri (Akdeniz, Karadeniz, Karasal) ve dağılışları incelendi." }, { text: "İklim ve bitki örtüsü ilişkisi kuruldu." }, { text: "Dilsiz harita üzerine iklim tipleri ve bitki örtüleri işlendi." }] },
    { title: "Coğrafya: Nüfus ve Yerleşme", description: "Türkiye'de nüfusun dağılışını etkileyen faktörleri, nüfus piramitlerini ve yerleşme tiplerini öğren.", checklist: [{ text: "Nüfus sayımları ve demografik verileri incele." }, { text: "Türkiye nüfus piramidini yorumla." }, { text: "Kırsal ve kentsel yerleşme arasındaki farkları analiz et." }, { text: "Göçlerin neden ve sonuçlarını çalış." }] },
    { title: "Felsefe: Bilgi Felsefesi (Epistemoloji)", description: "Bilginin kaynağı, imkanı, sınırları ve doğruluğu hakkındaki temel felsefi akımları (Rasyonalizm, Empirizm, Kritisizm, Pozitivizm vb.) araştırarak özet çıkar.", checklist: [{ text: "Doğru bilgi mümkün müdür? sorusuna verilen cevaplar incelendi." }, { text: "Bilginin kaynakları (akıl, deney, sezgi, vahiy) hakkında notlar alındı." }, { text: "Her bir felsefi akımın ana temsilcileri ve görüşleri listelendi." }, { text: "Konuyla ilgili en az 20 felsefe sorusu çözüldü." }] },
    { title: "İngilizce: Essay Yazma Pratiği (Argumentative)", description: "Verilen konu hakkında argümanlar geliştirerek, giriş, gelişme ve sonuç bölümlerinden oluşan bir 'argumentative essay' yaz.", checklist: [{ text: "Tez cümlesi (thesis statement) oluşturuldu." }, { text: "Her paragraf için ana fikir ve destekleyici fikirler belirlendi." }, { text: "Geçiş kelimeleri (transition words) kullanılarak paragraflar arası bağlantı sağlandı." }, { text: "Yazım ve dil bilgisi kontrolü (proofreading) yapıldı." }] },
    { title: "Genel: TYT Deneme Sınavı Analizi", description: "Son çözdüğün TYT deneme sınavının detaylı analizini yap. Yanlış ve boş bıraktığın soruların konularını belirle ve bu konular için bir tekrar planı oluştur.", checklist: [{ text: "Deneme sınavındaki tüm yanlışlar incelendi." }, { text: "Boş bırakılan soruların nedenleri analiz edildi." }, { text: "Yanlış ve boşların konu dağılımı çıkarıldı." }, { text: "Eksik konular için haftalık bir tekrar programı hazırlandı." }] },
    { title: "Genel: AYT Deneme Sınavı Analizi", description: "Son çözdüğün AYT deneme sınavının detaylı analizini yap. Özellikle kendi alanındaki (Sayısal, Eşit Ağırlık, Sözel, Dil) derslerdeki yanlış ve boşlarını belirle.", checklist: [{ text: "Her ders için doğru, yanlış ve boş sayıları not edildi." }, { text: "Yanlış yapılan soruların konuları tespit edildi." }, { text: "Boş bırakılan soruların nedenleri (bilgi eksikliği, süre yetmemesi vb.) analiz edildi." }, { text: "Eksik konular için bir haftalık yoğunlaştırılmış bir tekrar programı hazırlandı." }] },
  ],
  badges: [
    { id: BadgeID.FirstAssignment, name: "İlk Adım", description: "İlk ödevini başarıyla tamamladın!" },
    { id: BadgeID.HighAchiever, name: "Yüksek Başarı", description: "Not ortalaman 90'ın üzerinde!" },
    { id: BadgeID.PerfectScore, name: "Mükemmel Skor", description: "Bir ödevden 100 tam puan aldın!" },
    { id: BadgeID.GoalGetter, name: "Hedef Avcısı", description: "Haftalık hedeflerinin hepsine ulaştın!" },
    { id: BadgeID.StreakStarter, name: "Seri Başladı", description: "3 gün üst üste ödev teslim ettin." },
    { id: BadgeID.StreakMaster, name: "Seri Ustası", description: "7 gün üst üste ödev teslim ettin." },
    { id: BadgeID.OnTimeSubmissions, name: "Dakik Oyuncu", description: "5 ödevi zamanında teslim ettin." },
  ]
};