
import { User, Assignment, Message, UserRole, AssignmentTemplate, Resource, Goal, AssignmentStatus, Conversation, AcademicTrack, Badge, BadgeID } from '../types';

export const getMockData = () => {
    const users: User[] = [
      { id: 'coach-1', name: 'Ayşe Yılmaz', email: 'ayse.yilmaz@koc.com', role: UserRole.Coach, profilePicture: 'https://i.pravatar.cc/150?u=coach-1' },
      { id: 'student-1', name: 'Ali Veli', email: 'ali.veli@ogrenci.com', role: UserRole.Student, profilePicture: 'https://i.pravatar.cc/150?u=student-1', assignedCoachId: 'coach-1', gradeLevel: '12', academicTrack: AcademicTrack.Sayisal, parentIds: ['parent-1'], xp: 250, streak: 3, lastSubmissionDate: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(), earnedBadgeIds: [BadgeID.FirstAssignment, BadgeID.HighAchiever] },
      { id: 'student-2', name: 'Zeynep Kaya', email: 'zeynep.kaya@ogrenci.com', role: UserRole.Student, profilePicture: 'https://i.pravatar.cc/150?u=student-2', assignedCoachId: 'coach-1', gradeLevel: '11', academicTrack: AcademicTrack.EsitAgirlik, xp: 120, streak: 0, lastSubmissionDate: null, earnedBadgeIds: [BadgeID.FirstAssignment] },
      { id: 'student-3', name: 'Mehmet Öztürk', email: 'mehmet.ozturk@ogrenci.com', role: UserRole.Student, profilePicture: 'https://i.pravatar.cc/150?u=student-3', assignedCoachId: 'coach-1', gradeLevel: 'mezun', academicTrack: AcademicTrack.Sayisal, xp: 480, streak: 7, lastSubmissionDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), earnedBadgeIds: [BadgeID.FirstAssignment, BadgeID.HighAchiever, BadgeID.StreakStarter] },
      { id: 'student-4', name: 'Fatma Demir', email: 'fatma.demir@ogrenci.com', role: UserRole.Student, profilePicture: 'https://i.pravatar.cc/150?u=student-4', assignedCoachId: 'coach-1', gradeLevel: '10', academicTrack: AcademicTrack.Sozel, xp: 100, streak: 1, lastSubmissionDate: new Date().toISOString(), earnedBadgeIds: [BadgeID.FirstAssignment] },
      { id: 'student-5', name: 'Selin Doğan', email: 'selin.dogan@ogrenci.com', role: UserRole.Student, profilePicture: 'https://i.pravatar.cc/150?u=student-5', assignedCoachId: 'coach-1', gradeLevel: '12', academicTrack: AcademicTrack.Dil, xp: 50, streak: 0, lastSubmissionDate: null, earnedBadgeIds: [] },
      { id: 'superadmin-1', name: 'Admin User', email: 'admin@platform.com', role: UserRole.SuperAdmin, profilePicture: 'https://i.pravatar.cc/150?u=superadmin-1' },
      { id: 'parent-1', name: 'Veli Hanım', email: 'veli.hanim@aile.com', role: UserRole.Parent, profilePicture: 'https://i.pravatar.cc/150?u=parent-1', childIds: ['student-1'] },
    ];
    
    const conversations: Conversation[] = [
        { id: 'conv-1', participantIds: ['coach-1', 'student-1'], isGroup: false },
        { id: 'conv-2', participantIds: ['coach-1', 'student-2'], isGroup: false },
        { id: 'conv-3', participantIds: ['coach-1', 'student-3'], isGroup: false },
        { id: 'conv-4', participantIds: ['coach-1', 'student-4'], isGroup: false },
        { id: 'conv-announcements', participantIds: ['coach-1', 'student-1', 'student-2', 'student-3', 'student-4', 'student-5'], isGroup: true, groupName: "Duyurular", groupImage: 'https://cdn-icons-png.flaticon.com/512/1041/1041891.png', adminId: 'coach-1' },
        { id: 'conv-group-1', participantIds: ['coach-1', 'student-1', 'student-2'], isGroup: true, groupName: "Proje Grubu", adminId: 'coach-1' },
    ];

    const assignments: Assignment[] = [
        { id: 'asg-1', studentId: 'student-1', coachId: 'coach-1', title: 'Matematik Problemleri', description: 'Limit ve Türev konularında 20 problem çözülecek.', dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(), status: AssignmentStatus.Pending, grade: null, feedback: '', fileUrl: null, submittedAt: null, feedbackReaction: null, submissionType: 'file', coachAttachments: [], audioFeedbackUrl: null, textSubmission: null, fileName: '', videoDescriptionUrl: null, videoFeedbackUrl: null, studentVideoSubmissionUrl: null, studentAudioFeedbackResponseUrl: null, studentVideoFeedbackResponseUrl: null },
        { id: 'asg-2', studentId: 'student-1', coachId: 'coach-1', title: 'Fizik Deney Raporu', description: 'Basit sarkaç deneyi raporu hazırlanacak.', dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), status: AssignmentStatus.Graded, grade: 85, feedback: 'Raporun gayet başarılı, özellikle sonuç bölümünü çok iyi analiz etmişsin. Bir dahaki sefere hipotez kısmını daha detaylı yazabilirsin.', fileUrl: '#', fileName: 'fizik_raporu.pdf', submittedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), feedbackReaction: '👍', submissionType: 'file', coachAttachments: [], audioFeedbackUrl: null, textSubmission: null, videoDescriptionUrl: null, videoFeedbackUrl: null, studentVideoSubmissionUrl: null, studentAudioFeedbackResponseUrl: null, studentVideoFeedbackResponseUrl: null },
        { id: 'asg-10', studentId: 'student-1', coachId: 'coach-1', title: 'Haftalık Kitap Özeti', description: 'Bu hafta okuduğun kitabın özetini 300 kelimeyi geçmeyecek şekilde yaz.', dueDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(), status: AssignmentStatus.Pending, grade: null, feedback: '', fileUrl: null, submittedAt: null, feedbackReaction: null, submissionType: 'text', coachAttachments: [], audioFeedbackUrl: null, textSubmission: null, fileName: '', videoDescriptionUrl: null, videoFeedbackUrl: null, studentVideoSubmissionUrl: null, studentAudioFeedbackResponseUrl: null, studentVideoFeedbackResponseUrl: null },
        { id: 'asg-3', studentId: 'student-2', coachId: 'coach-1', title: 'Kompozisyon Yazımı', description: 'Küresel ısınmanın etkileri üzerine bir kompozisyon yazılacak.', dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(), status: AssignmentStatus.Submitted, grade: null, feedback: '', fileUrl: '#', fileName: 'kompozisyon.docx', submittedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), feedbackReaction: null, submissionType: 'file', coachAttachments: [], audioFeedbackUrl: null, textSubmission: null, videoDescriptionUrl: null, videoFeedbackUrl: null, studentVideoSubmissionUrl: null, studentAudioFeedbackResponseUrl: null, studentVideoFeedbackResponseUrl: null },
        { id: 'asg-4', studentId: 'student-2', coachId: 'coach-1', title: 'Kimya Formül Ezberi', description: 'Organik kimya temel formüllerini ezberle ve tamamlandı olarak işaretle.', dueDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), status: AssignmentStatus.Graded, grade: 100, feedback: 'Harika, formülleri ezberlemen gelecekteki konular için çok önemli. Böyle devam et!', fileUrl: null, submittedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(), feedbackReaction: null, submissionType: 'completed', coachAttachments: [], audioFeedbackUrl: null, textSubmission: null, fileName: '', videoDescriptionUrl: null, videoFeedbackUrl: null, studentVideoSubmissionUrl: null, studentAudioFeedbackResponseUrl: null, studentVideoFeedbackResponseUrl: null },
        { id: 'asg-11', studentId: 'student-2', coachId: 'coach-1', title: 'Biyoloji Çizimi', description: 'Bir bitki hücresinin organellerini çiz ve isimlendir. Çizimini yükle.', dueDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(), status: AssignmentStatus.Pending, grade: null, feedback: '', fileUrl: null, submittedAt: null, feedbackReaction: null, submissionType: 'file', coachAttachments: [], audioFeedbackUrl: null, textSubmission: null, fileName: '', videoDescriptionUrl: null, videoFeedbackUrl: null, studentVideoSubmissionUrl: null, studentAudioFeedbackResponseUrl: null, studentVideoFeedbackResponseUrl: null },
        { id: 'asg-5', studentId: 'student-3', coachId: 'coach-1', title: 'Tarih Araştırması', description: 'Fransız İhtilali\'nin Osmanlı\'ya etkilerini araştır ve bir sayfalık rapor yaz.', dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), status: AssignmentStatus.Pending, grade: null, feedback: '', fileUrl: null, submittedAt: null, feedbackReaction: null, submissionType: 'file', coachAttachments: [], audioFeedbackUrl: null, textSubmission: null, fileName: '', videoDescriptionUrl: null, videoFeedbackUrl: null, studentVideoSubmissionUrl: null, studentAudioFeedbackResponseUrl: null, studentVideoFeedbackResponseUrl: null }, // Overdue
        { id: 'asg-6', studentId: 'student-3', coachId: 'coach-1', title: 'Coğrafya Sunumu', description: 'Türkiye\'nin iklim tipleri hakkında bir sunum hazırla.', dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(), status: AssignmentStatus.Pending, grade: null, feedback: '', fileUrl: null, submittedAt: null, feedbackReaction: null, submissionType: 'file', coachAttachments: [], audioFeedbackUrl: null, textSubmission: null, fileName: '', videoDescriptionUrl: null, videoFeedbackUrl: null, studentVideoSubmissionUrl: null, studentAudioFeedbackResponseUrl: null, studentVideoFeedbackResponseUrl: null },
        { id: 'asg-12', studentId: 'student-3', coachId: 'coach-1', title: '50 Paragraf Sorusu', description: 'Verilen kaynaktan 50 paragraf sorusu çöz ve sonuçlarını metin olarak gönder.', dueDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(), status: AssignmentStatus.Graded, grade: 75, feedback: 'Soruları çözmüş olman güzel fakat bazı dikkatsizlik hataların var. Lütfen soruları daha dikkatli oku.', fileUrl: null, textSubmission: '50 soruda 38 doğru, 12 yanlış yaptım.', submittedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), feedbackReaction: '👍', submissionType: 'text', coachAttachments: [], audioFeedbackUrl: null, fileName: '', videoDescriptionUrl: null, videoFeedbackUrl: null, studentVideoSubmissionUrl: null, studentAudioFeedbackResponseUrl: null, studentVideoFeedbackResponseUrl: null },
        { id: 'asg-7', studentId: 'student-4', coachId: 'coach-1', title: 'İngilizce Kelime Testi', description: 'Verilen 100 kelimeyi ezberle ve kendini sına.', dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), status: AssignmentStatus.Submitted, grade: null, feedback: '', fileUrl: null, submittedAt: new Date().toISOString(), feedbackReaction: null, submissionType: 'completed', coachAttachments: [], audioFeedbackUrl: null, textSubmission: null, fileName: '', videoDescriptionUrl: null, videoFeedbackUrl: null, studentVideoSubmissionUrl: null, studentAudioFeedbackResponseUrl: null, studentVideoFeedbackResponseUrl: null },
        { id: 'asg-8', studentId: 'student-4', coachId: 'coach-1', title: 'Deneme Analizi', description: 'Son deneme sınavının analizini yap ve hatalarını çıkar.', dueDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(), status: AssignmentStatus.Graded, grade: 95, feedback: 'Analizin çok detaylı ve yerinde. Hatalarının üzerine gitmen seni başarıya ulaştıracaktır.', fileUrl: '#', fileName: 'deneme_analizi.xlsx', submittedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(), feedbackReaction: '👍', submissionType: 'file', coachAttachments: [], audioFeedbackUrl: null, textSubmission: null, videoDescriptionUrl: null, videoFeedbackUrl: null, studentVideoSubmissionUrl: null, studentAudioFeedbackResponseUrl: null, studentVideoFeedbackResponseUrl: null },
        { id: 'asg-9', studentId: 'student-4', coachId: 'coach-1', title: 'Felsefe Makalesi Okuma', description: 'Platon\'un "Devlet" eserinden belirlenen bölümü oku ve ana fikirleri çıkar.', dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(), status: AssignmentStatus.Pending, grade: null, feedback: '', fileUrl: null, submittedAt: null, feedbackReaction: null, submissionType: 'completed', checklist: [{id: 'chk-asg9-1', text: 'Belirlenen bölümü oku', isCompleted: false}, {id: 'chk-asg9-2', text: 'Bölümdeki ana fikirleri listele', isCompleted: false}, {id: 'chk-asg9-3', text: 'Kendi yorumunu ekle', isCompleted: false}], coachAttachments: [], audioFeedbackUrl: null, textSubmission: null, fileName: '', videoDescriptionUrl: null, videoFeedbackUrl: null, studentVideoSubmissionUrl: null, studentAudioFeedbackResponseUrl: null, studentVideoFeedbackResponseUrl: null },
        { id: 'asg-13', studentId: 'student-5', coachId: 'coach-1', title: 'Geometri Soru Bankası', description: 'Üçgenler konusu bitirilecek.', dueDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(), status: AssignmentStatus.Pending, grade: null, feedback: '', fileUrl: null, submittedAt: null, feedbackReaction: null, submissionType: 'completed', coachAttachments: [], audioFeedbackUrl: null, textSubmission: null, fileName: '', videoDescriptionUrl: null, videoFeedbackUrl: null, studentVideoSubmissionUrl: null, studentAudioFeedbackResponseUrl: null, studentVideoFeedbackResponseUrl: null },
        { id: 'asg-14', studentId: 'student-5', coachId: 'coach-1', title: 'Haftalık Deneme Sınavı', description: 'Bu haftaki deneme sınavına gir ve sonucunu yükle.', dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), status: AssignmentStatus.Submitted, grade: null, feedback: '', fileUrl: '#', submittedAt: new Date().toISOString(), feedbackReaction: null, submissionType: 'file', coachAttachments: [], audioFeedbackUrl: null, textSubmission: null, fileName: 'deneme_sonuc.pdf', videoDescriptionUrl: null, videoFeedbackUrl: null, studentVideoSubmissionUrl: null, studentAudioFeedbackResponseUrl: null, studentVideoFeedbackResponseUrl: null },
    ];
    
    const messages: Message[] = [
        { id: 'msg-1', senderId: 'student-1', conversationId: 'conv-1', text: 'Hocam merhaba, matematik ödevindeki 5. soruda takıldım. Yardımcı olabilir misiniz?', timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), type: 'text', readBy: ['coach-1', 'student-1'] },
        { id: 'msg-2', senderId: 'coach-1', conversationId: 'conv-1', text: 'Merhaba Ali, tabii ki. Hangi adımı anlamadığını söylersen oradan devam edelim.', timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(), type: 'text', readBy: ['student-1', 'coach-1'], reactions: {'👍': ['student-1']} },
        { id: 'msg-3', senderId: 'student-1', conversationId: 'conv-1', type: 'file', text: 'Türev alma kuralını uyguladıktan sonraki kısım hocam.', fileUrl: '#', fileName: 'soru_ekran_goruntusu.png', imageUrl: 'https://via.placeholder.com/300x200.png?text=Soru+Ekran+Görüntüsü', timestamp: new Date(Date.now() - 55 * 60 * 1000).toISOString(), readBy: ['coach-1', 'student-1'] },
        { id: 'msg-4', senderId: 'coach-1', conversationId: 'conv-2', text: 'Zeynep, kompozisyon ödevin gelmiş, en kısa zamanda değerlendireceğim.', timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(), type: 'text', readBy: ['student-2', 'coach-1'] },
        { id: 'msg-5', senderId: 'student-2', conversationId: 'conv-2', text: 'Teşekkürler hocam, bekliyorum 😊', timestamp: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(), type: 'text', readBy: ['coach-1', 'student-2'] },
        { id: 'msg-6', senderId: 'coach-1', conversationId: 'conv-announcements', type: 'announcement', text: 'Arkadaşlar merhaba, yarınki etüt saatimiz 15:00\'e alınmıştır. Herkesin katılımını bekliyorum.', timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(), readBy: ['coach-1', 'student-1', 'student-2', 'student-3', 'student-4'] },
        { id: 'msg-8', senderId: 'coach-1', conversationId: 'conv-announcements', type: 'announcement', text: 'Önemli: Gelecek hafta yapılacak olan deneme sınavı için konu dağılımları kütüphane bölümüne eklenmiştir. Göz atmayı unutmayın!', timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), readBy: ['coach-1', 'student-1'] },
        { id: 'msg-7', senderId: 'coach-1', conversationId: 'conv-3', type: 'poll', text: 'Anket: Gelecek haftaki deneme sınavı', poll: { question: 'Gelecek haftaki deneme sınavı hangi gün olsun?', options: [{text: 'Cumartesi', votes: ['student-3']}, {text: 'Pazar', votes: []}] }, timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(), readBy: ['student-3', 'coach-1'] },
        { id: 'msg-group-1', senderId: 'coach-1', conversationId: 'conv-group-1', type: 'system', text: 'Ayşe Yılmaz, Ali Veli ve Zeynep Kaya ile bir grup sohbeti başlattı.', timestamp: new Date(Date.now() - 10 * 60 * 1000).toISOString(), readBy: ['coach-1', 'student-1', 'student-2'] },
        { id: 'msg-group-2', senderId: 'coach-1', conversationId: 'conv-group-1', type: 'text', text: 'Merhaba arkadaşlar, bu grupta yeni proje ödevimizin detaylarını konuşacağız.', timestamp: new Date(Date.now() - 9 * 60 * 1000).toISOString(), readBy: ['coach-1', 'student-1', 'student-2'] },
    ];

    const templates: AssignmentTemplate[] = [
      { id: 'temp-task-1', title: 'Genel Soru Çözümü', description: 'Belirtilen konularda veya kaynaklardan belirli sayıda soru çözülecektir. Çözüm adımlarınızı göstermeniz ve anlamadığınız noktaları belirtmeniz beklenmektedir.', checklist: [{text: 'Belirtilen sayıda soruyu çöz'}, {text: 'Yanlışlarını ve boşlarını kontrol et'}, {text: 'Anlamadığın soruları not al'}] },
      { id: 'temp-task-2', title: 'Makale/Kompozisyon Yazımı', description: 'Verilen konu hakkında araştırma yaparak, giriş-gelişme-sonuç bölümlerinden oluşan bir yazı hazırlanacaktır.', checklist: [{text: 'Konu hakkında araştırma yap'}, {text: 'Yazı taslağını oluştur'}, {text: 'Yazıyı yaz ve dilbilgisi kontrolü yap'}] },
      { id: 'temp-math-1', title: 'Matematik Soru Çözümü', description: 'Belirtilen matematik konusundan 50 soru çözülecek. Çözülemeyen sorular işaretlenip derste sorulacak.', checklist: [{text: 'Konu tekrarı yap'}, {text: '50 soruyu çöz'}, {text: 'Yanlışlarını kontrol et'}, {text: 'Anlamadıklarını not al'}] },
      { id: 'temp-turkish-1', title: 'Türkçe Paragraf Analizi', description: 'Verilen paragraf setinden 20 soru çözülecek. Her sorunun analizi yapılacak.', checklist: [{text: 'Soruları süre tutarak çöz'}, {text: 'Yanlışların nedenlerini analiz et'}, {text: 'Bilmediğin kelimeleri not al'}] },
      { id: 'temp-physics-1', title: 'Fizik Konu Tekrarı', description: 'Bu haftanın fizik konusunu tekrar et ve özet çıkar.', checklist: [{text: 'Konu anlatım videosunu izle'}, {text: 'Ders notlarını tekrar et'}, {text: 'Konuyla ilgili 30 soru çöz'}] },
      { id: 'temp-exam-1', title: 'Deneme Sınavı Analizi', description: 'Son girdiğin deneme sınavının detaylı analizini yap. Yanlış ve boş bıraktığın soruların konularını belirle.', checklist: [{text: 'Sınav sonucunu sisteme gir'}, {text: 'Tüm yanlışları tek tek incele'}, {text: 'Yanlış yapılan konuların listesini çıkar'}, {text: 'Haftalık çalışma programına ekle'}] },
      { id: 'temp-reading-1', title: 'Kitap Okuma Raporu', description: 'Haftalık belirlenen kitabı oku ve 1 sayfalık özet ve yorum raporu hazırla.', checklist: [{text: 'Kitabı bitir'}, {text: 'Ana karakterleri ve olayı not al'}, {text: 'Kitap hakkındaki düşüncelerini yaz'}, {text: 'Raporu sisteme yükle'}] },
      { id: 'temp-mistake-1', title: 'Yanlış Soru Defteri', description: 'Hafta boyunca çözdüğün testlerdeki tüm yanlış soruları kesip yanlış defterine yapıştır ve doğru çözümünü öğren.', checklist: [{text: 'Tüm derslerdeki yanlışları belirle'}, {text: 'Soruları deftere yapıştır'}, {text: 'Doğru çözümü altına yaz'}, {text: 'Hafta sonu bu soruları tekrar çöz'}] },
    ];
    
    const resources: Resource[] = [
      { id: 'res-1', name: 'Türev Konu Anlatımı.pdf', type: 'pdf', url: '#', isPublic: false, uploaderId: 'coach-1', assignedTo: ['student-1'] },
      { id: 'res-2', name: 'Rehber Matematik - YouTube Kanalı', type: 'link', url: 'https://www.youtube.com/@RehberMatematik', isPublic: true, uploaderId: 'coach-1', assignedTo: [] },
      { id: 'res-3', name: 'Hücre Organelleri Videosu', type: 'video', url: '#', isPublic: false, uploaderId: 'coach-1', assignedTo: ['student-2'] },
      { id: 'res-4', name: 'Genel Fizik Formülleri', type: 'pdf', url: '#', isPublic: true, uploaderId: 'coach-1', assignedTo: [] },
      { id: 'res-5', name: 'Organik Kimya Giriş', type: 'pdf', url: '#', isPublic: true, uploaderId: 'coach-1', assignedTo: [] },
      { id: 'res-6', name: 'İleri Düzey Paragraf Soru Bankası', type: 'pdf', url: '#', isPublic: false, uploaderId: 'coach-1', assignedTo: ['student-3', 'student-4'] },
    ];
    
    const goals: Goal[] = [
        {id: 'goal-1', studentId: 'student-1', text: 'Haftada 200 paragraf sorusu çöz.', isCompleted: false},
        {id: 'goal-2', studentId: 'student-2', text: 'Her gün 20 yeni İngilizce kelime ezberle.', isCompleted: true},
        {id: 'goal-3', studentId: 'student-3', text: 'Gecikmiş tarih ödevini bu hafta bitir.', isCompleted: false},
        {id: 'goal-4', studentId: 'student-4', text: 'Haftalık deneme sınavı netini 5 puan artır.', isCompleted: false},
        {id: 'goal-5', studentId: 'student-5', text: 'Haftada en az 3 deneme çöz.', isCompleted: false},
    ];

    const badges: Badge[] = [
      { id: BadgeID.FirstAssignment, name: "İlk Adım", description: "İlk ödevini başarıyla teslim ettin!" },
      { id: BadgeID.HighAchiever, name: "Yüksek Başarı", description: "Not ortalaman 85'in üzerinde." },
      { id: BadgeID.PerfectScore, name: "Mükemmel Skor", description: "Bir ödevden 100 tam puan aldın." },
      { id: BadgeID.GoalGetter, name: "Hedef Avcısı", description: "İlk hedefini tamamladın." },
      { id: BadgeID.StreakStarter, name: "Seri Başlangıcı", description: "3 günlük ödev teslim serisi yakaladın." },
      { id: BadgeID.StreakMaster, name: "Seri Ustası", description: "7 günlük ödev teslim serisi yakaladın." },
      { id: BadgeID.OnTimeSubmissions, name: "Dakik Kahraman", description: "5 ödevi zamanında teslim ettin." },
    ];

    return { users, assignments, messages, templates, resources, goals, conversations, badges };
};
